### ISSUE TITLE
Feature Request - Pass DataFetchingEnvironment to the BatchLoader.

### ISSUE THREAD

**Issue by budjb** [graphql-java/java-dataloader#26]
The dataloader library seems to give me most of the functionality I'm looking for when trying to batch my DB queries for a layer of a graphql query. I am working with very large documents in the database I'm querying, and I'd rather optimize my queries to the database so that I only request the information from the database necessary to fulfill the graphql query.

I'm able to determine the required set of data based on the DataFetchingEnvironment that's passed to the DataFetcher, but I see no way to pass that information downstream to the BatchLoader. Having that object, or any other custom object containing the contextual data I need for that layer of the query, would enable the optimization I'm looking for.

**Comment by bbakerman** [comment]
I have just added a capability into the library to allow context to be provided to the batch loader function

```
BatchLoaderEnvironment batchLoaderEnvironment = BatchLoaderEnvironment.newBatchLoaderEnvironment()
                .context(SecurityCtx.getCallingUserCtx()).build();

        DataLoaderOptions options = DataLoaderOptions.newOptions()
                .setBatchLoaderEnvironmentProvider(() -> batchLoaderEnvironment);

        BatchLoaderWithContext<String, String> batchLoader = new BatchLoaderWithContext<String, String>() {
            @Override
            public CompletionStage<List<String>> load(List<String> keys, BatchLoaderEnvironment environment) {
                SecurityCtx callCtx = environment.getContext();
                return callDatabaseForResults(callCtx, keys);
            }
        };

        DataLoader<String, String> loader = DataLoader.newDataLoader(batchLoader, options);
```

Note it is NOT per `dataloader.load(key)` call because of the batching nature.  If I load keys A,B,C each with a `context` object then what context do I sent to the combined batch function?

Rather is is a provider model on the DataLoader options.  The provider of context is called when the batch load function is dispatched.

In the case of graphql you will need to have a "mutable" provider that you "set" target fields into.

**Comment by bbakerman** [comment]
This has been added in 2.1.1
