### ISSUE TITLE
Exception when using @RequestScope and async CompletableFuture

### ISSUE THREAD

**Issue by mattes3** [graphql-java/java-dataloader#30]
Hello,

when I use an asynchronous batch data loader together with a request-scoped DataLoader, the thing crashes when the batch data loader calls a backend service that needs a request-scoped JPA EntityManager.

This is because the asynchronous batch data loader starts a new thread, and the dependency injection framework (Ratpack/Guice in this case) does not find the request scope threadlocal any more.

How is this supposed to work?

Best...
Matthias 

P.S. As a work-around, I removed the asynchronous stuff and used CompletableFuture.completedFuture() in the Batch Loader, too.

**Comment by bbakerman** [comment]
This is not a graphql-java questions - this is a Ratpack/Guice question.  That is - how does one use multiple threads for concurrency and still access RequestScope components?

I dont know how to answer that because I have not used Ratpack/Guice in anger.

I do know its not a bug / design issue in graphql-java
