### ISSUE TITLE
How to controller dataloader scope

### ISSUE THREAD

**Issue by dailinyi** [graphql-java/java-dataloader#48]
In your readme.md, it says:
```
If you are serving web requests then the data can be specific to the user requesting it. If you have user specific data then you will not want to cache data meant for user A to then later give it user B in a subsequent request.

The scope of your DataLoader instances is important. You might want to create them per web request to ensure data is only cached within that web request and no more.

If your data can be shared across web requests then you might want to scope your data loaders so they survive longer than the web request say.
```

And the dataloader.java is not support extend,  such as #37 

So if a request has a same thread or a same tracer, can you provide some idea to the dataloader scope a request? such as Best Practice , etc.

**Comment by kaqqao** [comment]
This is talking about the scope of the object `DataLoader` object itself, i.e. whether you reuse the same instance for multiple requests or not.
You can create a new `DataLoaderRegistry` for each request if you don't want to share anything, or you can e.g. keep an instance in the session scope if you want to reuse an instance per user, or use the same instance always to share everything between the users - it's up to you. You can also have any sort of mapping between the request and the data loader by e.g. holding onto a global `ConcurrentHashMap<Key, DataLoaderRegistry>` (for whatever the appropriate `Key` is, maybe the user ID, maybe something else).
But since you're mentioning threads, it sounds like you simply want per-request behavior which the most straight-forward - just create a new `DataLoaderRegistry` per request, and the same instance will be reused for all the fields in the request.
Do not really tie your logic to the thread though as different threads can end up executing different resolvers and you're likely to shoot yourself in the foot.

**Comment by dailinyi** [comment]
Thank you for your solution. 

But our dataloaderRegistry have 60 or more dataloader registered,  So new `DataLoaderRegistry` per-request is too  heavy, it not fit us.
Let me think about how to solve it depends your idea

Thank you ones more....

**Comment by bbakerman** [comment]
> But our dataloaderRegistry have 60 or more dataloader registered, So new DataLoaderRegistry per-request is too heavy, it not fit us.

Sorry but this is simply not true.   Creating 60 data loaders and adding them to the DataLoaderRegsitry map per request if blazingly fast.

If you dont believe me : 

```
/**
 * See http://hg.openjdk.java.net/code-tools/jmh/file/tip/jmh-samples/src/main/java/org/openjdk/jmh/samples/ for more samples
 * on what you can do with JMH
 *
 * You MUST have the JMH plugin for IDEA in place for this to work :  https://github.com/artyushov/idea-jmh-plugin
 *
 * Install it and then just hit "Run" on a certain benchmark method
 */
@Warmup(iterations = 2, time = 5, batchSize = 3)
@Measurement(iterations = 3, time = 10, batchSize = 4)
public class NewDataLoaderBenchMark {

    static final BatchLoader batchLoadersAreStatelessAndCanBeReused = new BatchLoader() {
        @Override
        public CompletionStage<List> load(List keys) {
            return CompletableFuture.completedFuture(keys);
        }
    };

    @Benchmark
    @BenchmarkMode(Mode.Throughput)
    @OutputTimeUnit(TimeUnit.SECONDS)
    public void benchMark_CreateDataLoaderRegistry_Throughput() {
        executeTest();
    }

    @Benchmark
    @BenchmarkMode(Mode.AverageTime)
    @OutputTimeUnit(TimeUnit.MILLISECONDS)
    public void benchMark_CreateDataLoaderRegistry_AvgTime() {
        executeTest();
    }

    public static void executeTest() {

        DataLoaderRegistry registry = new DataLoaderRegistry();

        for (int i = 0; i < 60; i++) {
            DataLoader dataLoader = DataLoader.newDataLoader(batchLoadersAreStatelessAndCanBeReused);
            registry.register("" + i, dataLoader);
        }
    }
}
```

```
Benchmark                                                              Mode  Cnt      Score     Error  Units
NewDataLoaderBenchMark.benchMark_CreateDataLoaderRegistry_Throughput  thrpt   15  38424.035 ± 922.163  ops/s
NewDataLoaderBenchMark.benchMark_CreateDataLoaderRegistry_AvgTime      avgt   15      0.026 ±   0.001  ms/op
```

That is on my Mac it takes 0.02 of a millisecond to create the registry of 60 data loaders - thats per web request.  All things are relative but compared to getting the data in the query you wont notice it at all. 

And as Bojan says you code will be safer (no shared state)

Be careful of pre-optimising your design decisions - they can lead you to places of compromise when there was no need.
