### ISSUE TITLE
Add getIfCached(key) in DataLoader

### ISSUE THREAD

**Issue by MarcBridner** [graphql-java/java-dataloader#50]
It'd be great if the DataLoader had a getIfCached method returning the future (or the actual object) if it exists, without triggering a load. Alternatively if the DataLoader had it's member variables as protected so that the class could be extended.

We have a quite complicated setup with lots of relationships between entities as well as partial loading of some entities. Occasionally we want to check if an item is in the DL cache and use it if it is (and has the data we need), otherwise go down a different path. 

We also prime the cache of one data loader when loading a list of the same entities in a batch loader belonging to another data loader. 

We try to avoid chaining dataloader calls in a thenCompose due to manual invocation of dispatch() causing double loads of the same entity from the same data-loader, so we instead want to implement some slightly more intelligent batch loaders.

**Comment by bbakerman** [comment]
Are you think of a sifnature like

```
Optional<CompleteFuture<V>> loadIfCached(K key)
```

Where is returns the cached CF otherwise `Optinal.empty()`? 

 Remember the CF might not be resolved but its in the cache of CFs.  Also remember the cache is a cache of promises ot Values not the Values themselves.   You cant be sure the CF to Value has finished hence you cant really inspect it (I guess you can via `java.util.concurrent.CompletableFuture#isDone` but its pretty fiddly)

Is that what you are after?

**Comment by bbakerman** [comment]
if you could propose a change via a PR that would be great

**Comment by bbakerman** [comment]
I started a proof of concept here

https://github.com/graphql-java/java-dataloader/pull/52

Is this what you are after?

**Comment by MarcBridner** [comment]
Yes, that looks exactly like what I'm after. I was going to try to do something similar with a locally modified copy, but I guess you beat me to it :)

**Comment by bbakerman** [comment]
I have released 2.2.3 with `getIfPresent` and `getIfCompleted`

**Comment by MarcBridner** [comment]
Thank you! That was super fast :)
