### ISSUE TITLE
Dataloader return as async Fetcher

### ISSUE THREAD

**Issue by dailinyi** [graphql-java/java-dataloader#51]
My dataFetcher have some business logic, so need async.
How to use dataloader return some base data.
eg:
BuildWiring is :
```
RuntimeWiring.newRuntimeWiring()
                .type(newTypeWiring("Query")
                        .dataFetcher("bookById", AsyncDataFetcher.async(graphQLDataFetchers.getBookByIdDataFetcher(), pool)))
                .type(newTypeWiring("Book")
                        .dataFetcher("author", async(graphQLDataFetchers.getAuthorDataFetcher(), pool)))
                .build();
```
Fetcher.java is:
```
...
 DataLoader<Object, Object> characters = dataFetchingEnvironment.getDataLoader("books");
CompletableFuture<Object> book = characters.load(bookId);
return book;
```

The root cause is the `result` is CompletableFuture<CompletableFuture < Object > >,  but graphql only parsing a `.get()` method;

**Comment by bbakerman** [comment]
Have a look CompleteableFuture.thenCompose

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#thenCompose-java.util.function.Function-

Its effectively a `flatmap` on two CFs that means you get to chain together to steps that both produce CFs and present one

Also I think you need to change the data fetchers so that instead of wrapping them in `AsyncDataFetcher.async()` you code them to use the `CompleteableFuture.supplyAsync`

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#supplyAsync-java.util.function.Supplier-


```
        DataFetcher dataFetcher = new DataFetcher() {
            @Override
            public Object get(DataFetchingEnvironment environment) throws Exception {
                Supplier<String> fetchOfValue = new Supplier<String>() {
                    @Override
                    public String get() {
                        return "This is done async via a supplier and CompletableFuture.supplyAsync";
                    }
                };
                return CompletableFuture.supplyAsync(fetchOfValue);
            }
        };

```

HOWEVER....

if you are using DataLoader then typically you DONT need async data fetchers because the `org.dataloader.BatchLoader` is itself ready for an async value

Your BatchLoader of books should use `CompletableFuture.supplyAsync` and hence there is no need for `AsyncDataFetcher.async` to be used

**Comment by dailinyi** [comment]
Thank you for your answer.
In fact, my project is a common project. 
We abstract the `MODEL` and `DATASOURCE` .
`MODEL` like VOs, use by `front-end` such as web or app; and `DATASOURCE` like BOs, fetch data from database or other rpc. 
`Dataloader` take charge of batch load and cache a `DATASOURCE` .

A fetcher will returns a MODEL, but MODEL may from two DATASOURCE or more, even use DAG to process DATASOURCE dependency.
So a fetcher may consume a long time. It's why I use `AsyncDataFetcher.async` to get a fetcher.


Back to this question, I think your first suggest apply to two CFs serializability , such as flapMap. but this fact is CF1<CF2<Object>>, the `CF1` produce `AsyncDataFetcher.async` Fetchers , the `CF2` product dataloader.load in the Fetchers.

And the 2nd suggest async in fetcher of `Supplier`, or use AsyncDataFetcher.async is no difference I think. because I want async fetcher and dataloader.load is async to wait graphql execution to dispatchAll() also.

Of course, my question is not only belong to dataloader. It's a graphql-java Invocation process question. But it's bring by dataloader, so we discuss it in here.

**Comment by bbakerman** [comment]
Let me be more explicit.

When you use DataLoader you are trying to "batch" N calls by key to one batch load function.

Therefore your data fetchers should be just like

```
DataFetcher df  = env -> {
      return dataLoader.load(ev.getArg("myKey)
}
```

This will return a CF that is not resolved until dispatch is called and the batch load function is invoked

In your BatchLoad function you should do this

```
BatchLoader<K,V> batchLoader = keys -> {
   return CompleteableFuture.supplyAsync( () -> {
         return thisCallMakeTakeSomeTime(keys);
   });
}
```

This will be 100% async .  There is no need for AsyncDataFectcher etc... at the field data fetcher site.

**Comment by dailinyi** [comment]
Yeah, so I think the dataloader will above of DAG fetcher
Thx~
