### ISSUE TITLE
Won't compile on Windows (encoding issue)

### ISSUE THREAD

**Issue by etienne-sf** [graphql-java/java-dataloader#58]
Hello,

I get compilation error when compiling java_dataloader from the windows command prompt.

To solve this, I added this line in the gradle.properties file :
org.gradle.jvmargs=-Dfile.encoding=UTF-8

Etienne

**Comment by etienne-sf** [comment]
Hello,

I'm myself using Windows. 

I never encountered this issue. 

You closed it because it was not relevant ?
Or because you proposed a solution ?

Étienne

**Comment by bbakerman** [comment]
I close this because its old, has a work around and is probably fixed in
the latest gradle bumps

If it's still a problem then a PR to fix it for Windows people would be
appropriate.

I have the capability and inclination to develop on Mac and Linux - if
Windows people want to compile the code then they need to sort out any
friction via PRs contributed back.
